# Generated by Django 2.1.7 on 2019-11-14 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moniter', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='emergency',
        ),
        migrations.DeleteModel(
            name='heartrate',
        ),
    ]
